### ISSUE TITLE
feature request: full-covariance Gaussians

### ISSUE THREAD

**Issue by murphyk** [deepmind/distrax#34] opened 2021-07-17 04:11 UTC
It would be very useful to have a jax-native implementation of 
https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/MultivariateNormalFullCovariance

**Comment by freddy123098** [comment] 2022-01-13 12:41
Ok so can u give me the repo steps and we can get started.

**Comment by gpapamak** [comment] 2022-01-13 13:39
We are already working on supporting full-covariance Gaussians with various types of covariance matrix, so please bear with us. (Sorry to not have posted an update on this.)

**Comment by freddy123098** [comment] 2022-01-14 16:16
It's ok @gpapamak but the issue where do I start to solve this issue.

**Comment by freddy123098** [comment] 2022-01-14 16:17
And how to stop this issue from happening?

**Comment by freddy123098** [comment] 2022-01-15 08:54
@murphyk So can u provide more information please.

**Comment by freddy123098** [comment] 2022-01-15 08:54
On what the issue is.

**Comment by thomaspinder** [comment] 2022-03-01 09:58
Is there an update of this issue? I'd be happy to help if there's something specific that needs doing.

**Comment by franrruiz** [comment] 2022-03-01 10:51
Hi @thomaspinder: Thank you for following up! We are working on this as we speak and this will be released (hopefully) soon.

**Comment by murphyk** [comment] 2022-03-10 03:46
Is this the code?
https://github.com/deepmind/distrax/blob/master/distrax/_src/distributions/mvn_from_bijector.py

**Comment by franrruiz** [comment] 2022-03-10 08:30
Hi @murphyk : Almost :) This is intended to be a non-public class to support the different multivariate Gaussians, which are currently under internal review.

**Comment by gpapamak** [comment] 2022-03-25 15:00
UPDATE: This is now supported in Distrax v0.1.2.

We have added three new classes for full-covariance Gaussians (they parameterize the covariance matrix in different ways):
- `MultivariateNormalDiagPlusLowRank`
- `MultivariateNormalFullCovariance`
- `MultivariateNormalTri`

KL divergences between any combination of them or the multivariate Gaussians from TFP are supported.

**Closed by gpapamak** 2022-03-25 15:00 UTC
